# Generated by Django 4.0.3 on 2022-04-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='AgeCategory',
            field=models.PositiveIntegerField(choices=[(1, '18-24'), (2, '24-29'), (3, '30-34'), (4, '35-39'), (5, '40-44'), (6, '45-49'), (7, '50-54'), (8, '55-59'), (9, '60-64'), (10, '65-69'), (11, '70-74'), (12, '75-79'), (13, '80 or older')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='AlcoholDrinking',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Asthma',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='Diabetic',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='DiffWalking',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='GenHealth',
            field=models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='KidneyDisease',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PhysicalActivity',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Sex',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='SkinCancer',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Smoking',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Stroke',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='heartdisease',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], max_length=4, null=True),
        ),
    ]
