# Generated by Django 4.0.3 on 2022-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_alter_data_agecategory_alter_data_alcoholdrinking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Race',
            field=models.PositiveIntegerField(choices=[(1, 'Hispanic'), (2, 'Other'), (3, 'American Indian/Alaskan Native'), (4, 'Asian'), (5, 'Black'), (6, 'White')], max_length=20, null=True),
        ),
    ]
