# Generated by Django 4.0.3 on 2022-04-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0003_alter_data_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BMI',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='MentalHealth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PhysicalHealth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
