# Generated by Django 4.0.3 on 2022-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_alter_data_bmi_alter_data_mentalhealth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BMI',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='MentalHealth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PhysicalHealth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='SleepTime',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
