# Generated by Django 4.0.3 on 2022-04-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_alter_data_bmi_alter_data_mentalhealth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='heartdisease',
        ),
    ]
